apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: docker.io/vllm/vllm-openai
    newName: 012345678901.dkr.ecr.us-west-2.amazonaws.com/vllm-uccl-ep
    newTag: vllm0.21.0-uccl-0dc87eb-cu13-b300-fix1
patches:
  - path: patch-prefill-b300.yaml
    target: { kind: Deployment, name: prefill }
  - path: patch-decode-b300.yaml
    target: { kind: Deployment, name: decode }
