locals {
  backend_kms_key_id = coalesce(var.kms_key_id, "alias/aws/s3")

  backend_hcl = trimspace(
    <<-EOT
    # Generated by infra/eks/bootstrap.
    # Save this as ../backend.hcl next to the parent infra/eks module.
    # Terraform 1.9-compatible locking uses DynamoDB.
    # On Terraform 1.10+, you may replace `dynamodb_table` with `use_lockfile = true`.
    bucket         = "${aws_s3_bucket.state.bucket}"
    key            = "${var.state_key}"
    region         = "${var.region}"
    dynamodb_table = "${aws_dynamodb_table.lock.name}"

    encrypt    = true
    kms_key_id = "${local.backend_kms_key_id}"
    EOT
  )
}

resource "aws_s3_bucket" "state" {
  bucket = var.state_bucket_name
  tags   = var.tags
}

# Versioning is the recovery mechanism: a truncated or otherwise bad state write
# can be rolled back by promoting an older object version back to current.
resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    bucket_key_enabled = true

    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = var.kms_key_id
    }
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}

data "aws_iam_policy_document" "state_tls_only" {
  statement {
    sid    = "DenyInsecureTransport"
    effect = "Deny"

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.state.arn,
      "${aws_s3_bucket.state.arn}/*",
    ]

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "state" {
  bucket = aws_s3_bucket.state.id
  policy = data.aws_iam_policy_document.state_tls_only.json
}

# Keep versioning enabled forever for recovery, but expire noncurrent versions
# eventually so old state history does not grow without bound.
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = var.noncurrent_version_expiration_days
    }
  }

  depends_on = [aws_s3_bucket_versioning.state]
}

# Terraform 1.9 still needs DynamoDB for backend locking. Terraform 1.10+ can
# use `use_lockfile = true`, but the parent module supports 1.9 so the lock
# table keeps one backend config working across the full supported range.
resource "aws_dynamodb_table" "lock" {
  name         = var.lock_table_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"
  tags         = var.tags

  attribute {
    name = "LockID"
    type = "S"
  }
}
